### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by headering** [NeusZimmer/ONNX-ModularUI-StableDiffusion#1]
Loading default provider values:CPU
External Module wildcards_module Loaded
External Module styles_module Loaded
Traceback (most recent call last):
  File "D:\ONNX\ONNX-StableDiffusion.py", line 97, in <module>
    demo =init_ui()
  File "D:\ONNX\ONNX-StableDiffusion.py", line 20, in init_ui
    Img2Img_ui.show_Img2Img_ui()
  File "D:\ONNX\UI\Img2Img_ui.py", line 25, in show_Img2Img_ui
    image_t0 = gr.Image(
  File "C:\Users\it's me\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 152, in wrapper
    return fn(self, **kwargs)
TypeError: Image.__init__() got an unexpected keyword argument 'tool'

**Comment by headering** [comment]
Fix, that work for me: pip install gradio==3.50.2

**Comment by NeusZimmer** [comment]
Yes, new version of gradio  missed some previous component....I will specify version 3.50.2 in the requirements file
